site_name: reconPoint
site_author: KhulnaSoft DevSec
site_url: https://recon.khulnasoft.com
site_description: reconPoint is an automated reconnaissance framework meant for information gathering during penetration testing of web applications. reconPoint has customizable scan engines, which can be used to scan the websites, endpoints, and gather information.

copyright: "Copyright &copy; 2023 KhulnaSoft DevSec"

repo_url: https://github.com/khulnasoft/reconpoint
repo_name: reconPoint

theme:
  name: material
  custom_dir: docs/overrides
  logo: static/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: static/favicon.ico
  palette:
    scheme: light
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage/index.md
  - Scan Engine Configuration: usage/scan_engine.md
  - Changelog: changelog.md
  # - API: api/index.md

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/khulnasoft/reconpoint
    - icon: fontawesome/brands/discord
      link: https://discord.gg/H6WzebwX3H
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ojhayogesh11

extra_css:
  - assets/style.css

plugins:
  - search
  - badges
